#!/usr/bin/env fish

function safe_symlink -a to from
    if test -L $from
        echo "safe_symlink: removing existing symlink $from"
        rm $from
    end
    if test -e $from
        ls -l $from
        test (read -P "delete $from? (y/N) ") = "y" || return
        rm -r $from
    end
    echo "safe_symlink: creating $from -> $to"
    mkdir -p (dirname $from)
    wln -sT $to $from
end

set root (pwd)
not set -q USERPROFILE && set USERPROFILE $HOME
not set -q LOCALAPPDATA && set LOCALAPPDATA $HOME/.config

safe_symlink (nativepath $root/lazygit/config.yml) $LOCALAPPDATA/lazygit/config.yml
safe_symlink (nativepath $root/textadept/init.lua) $USERPROFILE/.textadept/init.lua
