#!/usr/bin/env fish

function safe_symlink -a to from
    if test -L $from
        echo "safe_symlink: removing existing symlink $from"
        rm $from
    end
    if test -e $from
        ls -l $from
        test (read -P "delete $from? (y/N) ") = "y" || return
        rm -r $from
    end
    echo "safe_symlink: creating $from -> $to"
    mkdir -p (dirname $from)
    ln -sT $to $from
end

set root (pwd)

safe_symlink $root/lazygit/config.yml $HOME/.config/lazygit/config.yml
