#!/usr/bin/env fish

function link-home
    set cwd (pwd)
    for f in $argv
        set dest $HOME/$f
        mkdir -p (dirname $dest)
        ln -sT $cwd/$f $dest
    end
end

link-home \
    .config/ranger \
    .my-config/* \
    .config/fish/* \
    (find \
        .config/Code \
    -type f)

if test -e private
    cd private

    link-home \
        .password-store \
        Documents/* \
        .my-config/*
end

ln -s Code $HOME/.config/'Code - OSS'
