#!/usr/bin/env bash

print_help() {
    # Print the file as the default help text.
    echo "### file $(realpath $0)"
    cat $0
}

while true; do
    case "$1" in
    -h|--help)
        print_help
        exit 0
        ;;
    *)
        break
        ;;
    esac
    shift
done

