#!/bin/bash
set -u

print_help() {
    echo "no help available, sorry"
}

while true; do
    case "$1" in
    -h|--help)
        print_help
        exit 0
        ;;
    *)
        break
        ;;
    esac
    shift
done

cd "$(dirname "$0")" || exit 1
