#!/usr/bin/env fish

argparse "h/help" -- $argv
or exit 1

# Print the script as a default --help action
if set -q _flag_help; and test -e (status filename)
    echo "### file "(status filename)
    cat (status filename)
    exit
end

