#!/usr/bin/env fish

argparse "h/help" -- $argv
or exit 1

# Print the script as a default --help action
function print_help
    test -e (status filename); or return
    echo "### file "(status filename)
    cat (status filename)
end

if set -q _flag_help
    print_help
    exit
end
