#!/usr/bin/env fish

argparse "h/help" -- $argv
or exit 1

# Print the script as a default --help action
function print_help
    echo "no help, sorry"
end

if set -q _flag_help
    print_help
    exit
end
